version: "3.9"
services:
  server:
    build: /
    ports:
      - '8080:8080'
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: "mysql:8"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
    ports:
      - '3306:3306'
    volumes:
      - my-mysql:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 30s
      retries: 10

volumes:
  my-mysql: